global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'driver-service'
    static_configs:
      - targets: ['driver-service:8001']
        labels:
          group: 'riderx'

  - job_name: 'ride-service'
    static_configs:
      - targets: ['ride-service:8002']
        labels:
          group: 'riderx'

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8003']
        labels:
          group: 'riderx'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']